name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Approvals labeler
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: Ready to merge
        REMOVE_LABEL: "awaiting%20review"
        
